#!/bin/sh

# Custom key mappings using xmodmap and setxkbmap

# Increase key speed via a rate change
xset r rate 300 50

# Turn on mousekeys
#setxkbmap -option keypad:pointerkeys

# Map the caps lock key to backspace
#setxkbmap -option caps:backspace

# Map the menu button to right super
xmodmap -e 'keycode 135 = Super_R'

# Map the caps lock key to backspace
#xmodmap -e 'keycode 66 = BackSpace'
#xmodmap -e 'clear Lock'

# Sym the caps lock key to backspace
#xmodmap -e 'remove lock = Caps_Lock'
#xmodmap -e 'keysym Caps_Lock = BackSpace'

# Swap the caps lock and backspace
# xmodmap -e 'keycode 22 = Caps_Lock'
# xmodmap -e 'keycode 66 = BackSpace'
# xmodmap -e "clear Lock"
